#include "PluginEditor.h"

// Binary data (generated by CMake juce_add_binary_data)
namespace nova_motion_BinaryData {
    extern const char* index_html;
    extern const int   index_htmlSize;
    extern const char* js_index_js;
    extern const int   js_index_jsSize;
    extern const char* js_juce_index_js;
    extern const int   js_juce_index_jsSize;
    extern const char* js_juce_check_native_interop_js;
    extern const int   js_juce_check_native_interop_jsSize;
    extern const char* n_logo_png;
    extern const int   n_logo_pngSize;
}

// ── Resource provider ──────────────────────────────────────────────────────────
static std::optional<juce::WebBrowserComponent::Resource>
getResource (const juce::String& url)
{
    using R = juce::WebBrowserComponent::Resource;

    auto strip = [](const juce::String& u) -> juce::String {
        auto s = u.fromFirstOccurrenceOf("/", false, false);
        if (auto q = s.indexOfChar('?'); q >= 0) s = s.substring(0, q);
        return s;
    };

    const auto path = strip(url);

    if (path == "index.html" || path.isEmpty())
        return R { std::vector<std::byte>((std::byte*)nova_motion_BinaryData::index_html,
                                          (std::byte*)nova_motion_BinaryData::index_html + nova_motion_BinaryData::index_htmlSize),
                   "text/html" };

    if (path == "js/index.js")
        return R { std::vector<std::byte>((std::byte*)nova_motion_BinaryData::js_index_js,
                                          (std::byte*)nova_motion_BinaryData::js_index_js + nova_motion_BinaryData::js_index_jsSize),
                   "application/javascript" };

    if (path == "js/juce/index.js")
        return R { std::vector<std::byte>((std::byte*)nova_motion_BinaryData::js_juce_index_js,
                                          (std::byte*)nova_motion_BinaryData::js_juce_index_js + nova_motion_BinaryData::js_juce_index_jsSize),
                   "application/javascript" };

    if (path == "js/juce/check_native_interop.js")
        return R { std::vector<std::byte>((std::byte*)nova_motion_BinaryData::js_juce_check_native_interop_js,
                                          (std::byte*)nova_motion_BinaryData::js_juce_check_native_interop_js + nova_motion_BinaryData::js_juce_check_native_interop_jsSize),
                   "application/javascript" };

    if (path == "n_logo.png")
        return R { std::vector<std::byte>((std::byte*)nova_motion_BinaryData::n_logo_png,
                                          (std::byte*)nova_motion_BinaryData::n_logo_png + nova_motion_BinaryData::n_logo_pngSize),
                   "image/png" };

    return std::nullopt;
}

// ── Editor ─────────────────────────────────────────────────────────────────────
NovaMotionFXEditor::NovaMotionFXEditor (NovaMotionFXProcessor& p)
    : AudioProcessorEditor (&p), processor (p)
{
    auto options = juce::WebBrowserComponent::Options {}
        .withNativeIntegrationEnabled()
        .withResourceProvider ([] (const juce::String& url) { return getResource(url); });

   #if JUCE_WINDOWS
    options = options.withBackend (juce::WebBrowserComponent::Options::Backend::webview2)
                     .withWinWebView2Options (
                         juce::WebBrowserComponent::Options::WinWebView2 {}
                             .withUserDataFolder (
                                 juce::File::getSpecialLocation (juce::File::tempDirectory)
                                     .getChildFile ("NovaMotionFX")));
   #endif

    // Native function: parameter change from JS → processor
    options = options.withNativeFunction ("paramChange", [this] (auto& args, auto complete) {
        if (!args.empty()) {
            const auto json = juce::JSON::parse (juce::String (args[0].toString()));
            if (auto* obj = json.getDynamicObject()) {
                const auto param  = obj->getProperty ("param").toString();
                const float value = (float) obj->getProperty ("value");
                if (auto* p = processor.apvts.getParameter (param))
                {
                    p->beginChangeGesture();
                    p->setValueNotifyingHost (value);
                    p->endChangeGesture();
                }
            }
        }
        complete ("ok");
    });

    webView = std::make_unique<juce::WebBrowserComponent> (options);
    addAndMakeVisible (*webView);

    const auto url = juce::WebBrowserComponent::getResourceProviderRoot() + "index.html";
    webView->goToURL (url);

    setResizable (false, false);
    setSize (1400, 860);
    startTimerHz (30);
}

NovaMotionFXEditor::~NovaMotionFXEditor() { stopTimer(); }

void NovaMotionFXEditor::paint (juce::Graphics& g) { g.fillAll (juce::Colour (0xff111113)); }
void NovaMotionFXEditor::resized() { if (webView) webView->setBounds (getLocalBounds()); }

void NovaMotionFXEditor::timerCallback()
{
    if (!webView || !webView->isVisible()) return;
    const float l = processor.peakL.load();
    const float r = processor.peakR.load();
    const auto script = juce::String ("if(window.updateMeters)updateMeters(") + l + "," + r + ");";
    webView->evaluateJavascript (script);
}
