name: Build Nova Tone Windows

on:
  push:
    paths:
      - 'Nova Tone/**'
      - '.github/workflows/build-nova-tone-windows.yml'
  pull_request:
    paths:
      - 'Nova Tone/**'
      - '.github/workflows/build-nova-tone-windows.yml'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CMake
        uses: lukka/get-cmake@v4.3.1

      - name: Clean build directory
        run: if (Test-Path "Nova Tone/build") { Remove-Item -Recurse -Force "Nova Tone/build" }

      - name: Configure CMake
        run: cmake -S "Nova Tone" -B "Nova Tone/build"

      - name: Build
        run: cmake --build "Nova Tone/build" --config Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NovaTone-Windows-build
          path: Nova Tone/build
