name: Build Nova Level Windows

on:
  push:
    paths:
      - 'Nova Level/**'
      - '.github/workflows/build-nova-level-windows.yml'
  pull_request:
    paths:
      - 'Nova Level/**'
      - '.github/workflows/build-nova-level-windows.yml'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CMake
        uses: lukka/get-cmake@v4.3.1

      - name: Clean build directory
        run: if exist "Nova Level\\build" rmdir /s /q "Nova Level\\build"

      - name: Configure CMake
        run: cmake -S "Nova Level" -B "Nova Level/build"

      - name: Build
        run: cmake --build "Nova Level/build" --config Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NovaLevel-Windows-build
          path: Nova Level/build
