name: Build Nova Curve macOS

on:
  workflow_dispatch:
  push:
    paths:
      - 'Nova Curve/**'
      - '.github/workflows/build-nova-curve-macos.yml'
  pull_request:
    paths:
      - 'Nova Curve/**'
      - '.github/workflows/build-nova-curve-macos.yml'

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CMake
        run: brew install cmake

      - name: Clean build directory
        run: rm -rf "Nova Curve/build"

      - name: Configure CMake
        run: cmake -S "Nova Curve" -B "Nova Curve/build"

      - name: Build
        run: cmake --build "Nova Curve/build" --config Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NovaCurve-macOS-build
          path: Nova Curve/build